// enum.js

export const INDUSTRIES = [
  "Technology",
  "Healthcare",
  "Finance",
  "Education",
  "Retail",
  "Manufacturing",
  "Entertainment",
  "Media",
  "Travel & Hospitality",
  "Real Estate",
  "Construction",
  "Energy",
  "Agriculture",
  "Transportation & Logistics",
  "Legal Services",
  "Consulting",
  "Food & Beverage",
  "Non-Profit",
  "Environmental Services",
  "Sports",
  "Automotive",
  "Aerospace",
  "Biotechnology",
  "E-Commerce",
  "Telecommunications",
  "Artificial Intelligence",
  "Cybersecurity",
  "Medical Devices",
  "Wellness",
  "Insurance",
  "Fintech",
  "Wealth Management",
  "K-12 Education",
  "Higher Education",
  "E-Learning",
  "Educational Technology",
  "Public Transport",
  "Waste Management",
  "Recycling",
  "Legal Tech",
  "Corporate Legal Departments",
  "Fashion",
  "Electronics",
  "Grocery",
  "Consumer Goods",
  "Streaming Services",
  "Publishing",
  "Broadcasting",
  "Tourism",
  "Hotels & Resorts",
  "Airlines",
  "Travel Agencies",
  "Residential",
  "Commercial",
  "Property Management",
  "Engineering",
  "Animal Husbandry",
  "Agricultural Technology",
  "Shipping",
  "Logistics",
  "Railways",
  "Public Transport",
  "Charitable Organizations",
  "Foundations",
  "Advocacy Groups",
  "Fitness & Recreation",
  "Arts & Culture",
  "Other",
];

// enum.js

export const CONTENT = [
  "Lifestyle",
  "Beauty",
  "Fashion",
  "Travel",
  "Food & Drink",
  "Fitness & Health",
  "Tech & Gadgets",
  "Gaming",
  "Education & Tutorials",
  "Parenting",
  "Finance & Investments",
  "Entertainment",
  "Music",
  "Photography",
  "Art & Design",
  "DIY & Crafts",
  "Home & Garden",
  "Sports",
  "Books & Literature",
  "Culture & Society",
  "Animals & Pets",
  "Motivation & Inspiration",
  "Politics & Current Affairs",
  "Business & Entrepreneurship",
  "Cars & Automotive",
  "Movies & TV Shows",
  "Reviews & Unboxings",
  "Events & Experiences",
  "Productivity & Personal Development",
  "Technology & Innovations",
  "Environmental Awareness",
  "Spirituality & Mindfulness",
  "Health & Wellness",
  "Food Recipes",
  "Travel Guides",
  "Fashion Trends",
  "Beauty Tips",
  "Tech Reviews",
  "Gaming Tutorials",
  "Fitness Routines",
  "Art Techniques",
  "Music Reviews",
  "Book Reviews",
  "Cultural Insights",
  "Pet Care Tips",
  "Motivational Quotes",
  "Political Commentary",
  "Business Strategies",
  "Automotive Reviews",
  "Movie Critiques",
  "Event Highlights",
];
